      - name: Sync and Add Android
        run: |
          npx cap add android || true
          npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
